consumers:
  list:
    consumer1:
      replicaCount: 2
      args: ["my", "arguments"]
      # disableMetrics: true  # By default, metrics are enabled, you can explicitely disable them
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 3
        describedService: "my-service"
        metricName: "m"
        metricMatchLabels:
          queue: queue_name
        targetMetricValue: ""
      expectedDeploymentScalePriority: 0
    consumer2:
      replicaCount: 2
      args: ["my", "arguments"]
      # disableMetrics: true  # By default, metrics are enabled, you can explicitely disable them
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 3
        describedService: "my-service"
        metricName: "m"
        metricMatchLabels:
          queue: queue_name
        targetMetricValue: ""
      expectedDeploymentScalePriority: 0
